### ISSUE TITLE
Update for new season

### ISSUE THREAD

**Issue by jscott0918** [flipperbw/FantasyPlus#11]
Hey FantasyPlus folks!  New season is upon us, and it looks like there have been some adjustments in page positions.  I am getting weird numbers 
![image](https://cloud.githubusercontent.com/assets/1441007/9725314/edf4abd8-55b1-11e5-8220-783aba3c3576.png) for the projected points. I will poke around and see if I can come up with a fix, but if anyone can beat me to it I would appreciate it greatly!

**Comment by Raab70** [comment]
I am getting a similar issue. I too am getting the season projections instead of the week 1 projections but it appears that my injury average (iAVG) calculation is also not working. 
![fantasy](https://cloud.githubusercontent.com/assets/6979384/9734854/01f1d5d0-55fc-11e5-9914-ce5d7f51aac9.png)

**Comment by flipperbw** [comment]
They didn't switch it over yet at FantasyPros, iAvg is for the new season since this is technically week 1, and FantasySharks is down. Fix is going out for the first.
