### ISSUE TITLE
Few players missing FantasyPros projections

### ISSUE THREAD

**Issue by miabbott** [flipperbw/FantasyPlus#12]
I've noticed that T.J. Yeldon (on my team) consistently does not have any weekly projections listed from FPros.  While digging into this some more, I noticed Blake Bortles (free agent in my league) seems to suffer the same problem.  See the screenshots below.

I checked on FantasyPros and confirmed both players are known and have projections.

http://www.fantasypros.com/nfl/projections/tj-yeldon.php

http://www.fantasypros.com/nfl/projections/blake-bortles.php

Blake Bortles listed in the Free Agents page
![bortles](https://cloud.githubusercontent.com/assets/10236257/10345411/683e47d0-6cf7-11e5-830f-6ec56a321db9.png)

T.J. Yeldon listed on the My Team page
![yeldon](https://cloud.githubusercontent.com/assets/10236257/10345410/683d974a-6cf7-11e5-9a04-7b3d22783c93.png)

**Comment by flipperbw** [comment]
Have you updated to 2.0.5? I fixed JAX/JAC players (ESPN changed the team name I think).

**Comment by miabbott** [comment]
That fixed it; I was still at 2.0.3.  Thanks!
