### ISSUE TITLE
You are currently viewing league history pages from the 2015 season.

### ISSUE THREAD

**Issue by lazloth** [flipperbw/FantasyPlus#13]
Howdy, noticed that any player activity (eg., propose trade) with extension enabled throws this or similar error:
![2015 oops](http://i.imgur.com/olQFc3E.png)

_-- Using chrome (Version 52.0.2743.116 (64-bit)) on mac, league is espn_

**Comment by flipperbw** [comment]
Hmm, I dont have any leagues yet to test this with. Does it reset immediately after you hit "click here to return to the 2016 league office"?

ESPN is pretty stupid with this - if you even for a second request a 2015 page, it sets that year as the year for all your future actions in the league.

**Comment by lazloth** [comment]
ESPN is very stupid with navigating previous years, I know. A rogue line in the LM, clicking on an old msg, etc ... 

Yes, it resets back to current but any actions touching players reverts to previous year again. I'll grab your js files and glance through but I'm many years removed from coding.

**Comment by flipperbw** [comment]
I can look when I get home, thanks for reporting. I have to do some funky stuff with the years before the season starts. Is it only for trading or also for adding/dropping?

**Comment by lazloth** [comment]
Yep, add/drops are affected. Plain free agent search sometimes as well but I didn't get too rigorous in testing. I've got a house full of kids tonight but should have time when the sugar ebbs to hunt a bit.

**Comment by flipperbw** [comment]
I think I have a fix/workaround in place. Can you please test the new version out when it's pushed to the store? (2.1.7)

**Comment by lazloth** [comment]
Loaded locally from here, looks like that did the trick! Thanks flipper :)

**Comment by flipperbw** [comment]
Thanks for submitting the issue, would have been bad for the next few weeks! I'll close, but please reopen if it's still an issue.
