### ISSUE TITLE
D/ST showing up as full seasons points (as opposed to one game)

### ISSUE THREAD

**Issue by cjappl** [flipperbw/FantasyPlus#14]
Chrome
Mac OSX 10.10.5
ESPN Private League (ESPN default scoring)

See attached screenshot. All players look fine on the predictions page, however the defenses are significantly higher in points, I believe this is their season projection as opposed to a game projection?

As much as I want the Texan's D to net me 101 points this week, I don't think that's going to happen

<img width="1018" alt="screen shot 2016-08-30 at 9 03 40 am" src="https://cloud.githubusercontent.com/assets/14171107/18096902/ad624cf8-6e90-11e6-9712-7d3122953672.png">
<img width="1197" alt="screen shot 2016-08-30 at 9 03 10 am" src="https://cloud.githubusercontent.com/assets/14171107/18096899/ad59dd0c-6e90-11e6-9295-64e926c05b9f.png">
<img width="1116" alt="screen shot 2016-08-30 at 9 02 40 am" src="https://cloud.githubusercontent.com/assets/14171107/18096901/ad5df91e-6e90-11e6-90ed-64c85d91e7b7.png">

**Comment by flipperbw** [comment]
FantasySharks, which is the only thing that offers DST/IDP projections, is broken right now. Their pages are either down or just showing the season rank. I can't do anything until they fix their problems, so best to just ignore it for now and look at rank.

**Comment by cjappl** [comment]
Cool, just wanted to track it in case it was on your side! Great tool btw

**Comment by flipperbw** [comment]
Thanks very much! If it persists as an issue, I'll take a deeper look.

**Comment by cjappl** [comment]
Can confirm problem has been fixed! D/ST back to a reasonable range
