### ISSUE TITLE
Changing tabs on ESPN causes duplicate Target fields

### ISSUE THREAD

**Issue by caebeman** [flipperbw/FantasyPlus#18]
After clicking on a WR or RB on ESPN  each time you switch to a tab for the first time a new TGTS field will be added.

**Comment by flipperbw** [comment]
Are you sure you aren't thinking of the FantasyTargets extension?

**Comment by waylonrobert** [comment]
I cannot reproduce this error.

**Comment by caebeman** [comment]
It was the FantasyTargets extension, sorry for the confusion.
