### ISSUE TITLE
Unable to submit lineup change with this extension enabled (ESPN)

### ISSUE THREAD

**Issue by dtcarls** [flipperbw/FantasyPlus#21]
Unable to submit lineup change with this extension enabled on ESPN. I am able to move players around, but when submit is clicked nothing happens and no errors within the console. When I disable this extension I am able to submit changes.

I thought it might have to do with the conflict with the FantasyTargets extension (https://github.com/tcbeutler/FantasyTargets/issues/5) however, I disabled FT and left FP enabled and same issue.

**Comment by flipperbw** [comment]
Should fix itself tomorrow or Wednesday at the latest. I'll fix this permanently at some point.

**Comment by flipperbw** [comment]
Is this working for you now? I'm able to do it without issue today.

**Comment by dtcarls** [comment]
Yes, issue resolved, weird bug
