### ISSUE TITLE
Permissions for all websites, seems more aggressive than necessary

### ISSUE THREAD

**Issue by flushentitypacket** [flipperbw/FantasyPlus#23]
>Read and change your data on all websites you visit

This seems unnecessary. Why not only give permissions for just ESPN/Yahoo/FF?

**Comment by flipperbw** [comment]
I've explained this a lot, but it's ESPN, Yahoo, Fleaflicker, FantasyPros, FantasySharks, depth chart info, etc. As I add new features I add new sites. If I add a permission for a new site, chrome disables the entire extension literally every single time. 

If you don't like that rule feel free to just download the code and run it yourself.

**Comment by flushentitypacket** [comment]
👍  Thanks for the explanation!
