### ISSUE TITLE
trend sparkline data wrong

### ISSUE THREAD

**Issue by williamadba** [flipperbw/FantasyPlus#27]
![mattbryant_trendline_20171108](https://user-images.githubusercontent.com/6641470/32579569-190a1c5c-c4a7-11e7-9c7a-1360baab2b1f.png)

sparkline data shows "out" for ATL K Matt Bryant when he wasn't out.

**Comment by flipperbw** [comment]
You're right, something is wrong with that. I actually thought I pushed a fix for this last week though. I'll check again.

**Comment by williamadba** [comment]
No problem, great job so far, keep it up

**Comment by flipperbw** [comment]
Try version 3.3.1 and let me know if that fixes it.

**Comment by williamadba** [comment]
cool! The graph now appears to be correct, but the hover texts don't match up.

**Comment by flipperbw** [comment]
What do you mean exactly?

**Comment by williamadba** [comment]
example:
![ss2017112](https://user-images.githubusercontent.com/6641470/32704479-7244ba30-c7cb-11e7-8a8f-8ab1399151ae.png)

**Comment by flipperbw** [comment]
Huh. Very strange, I cleared the entire storage cache so not sure how that's possible. What about if you click the FantasyPlus extension icon and hit "Refresh Data"?

**Comment by williamadba** [comment]
hm. I don't have that option when i click the icon. However it has been 30 minutes and that's what i have the refresh rate at

**Comment by flipperbw** [comment]
Go on one of your team pages and click it.

**Comment by williamadba** [comment]
i refreshed, that didn't help, went back to a flat sparkline. I uninstalled, reinstalled. No change.

**Comment by flipperbw** [comment]
Sorry you're having these issues. It's working fine for me - if you open up the dev console (right click on the page -> inspect element -> console) do you see any red errors?

**Comment by williamadba** [comment]
a few

I use ESPN


clubhouse?leagueId=424204&teamId=1&seasonId=2017:32 GET http://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ clubhouse?leagueId=424204&teamId=1&seasonId=2017:32
(anonymous) @ clubhouse?leagueId=424204&teamId=1&seasonId=2017:32
clubhouse?leagueId=424204&teamId=1&seasonId=2017:594 GET http://widgets.outbrain.com/outbrain.js net::ERR_BLOCKED_BY_CLIENT
espn-ads-external.js?xhr=1:1 GET https://www.googletagservices.com/tag/js/gpt.js net::ERR_NAME_NOT_RESOLVED
(anonymous) @ espn-ads-external.js?xhr=1:1
(anonymous) @ espn-ads-external.js?xhr=1:1
secure-us.imrworldwide.com/cgi-bin/m?ci=us-903969h&cg=0&cc=1&si=http%3A//games.espn.com/ffl/clubhouse%3FleagueId%3D424204%26teamId%3D1%26seasonId%3D2017&rp=&ts=compact&rnd=1510540168588:1 GET http://secure-us.imrworldwide.com/cgi-bin/m?ci=us-903969h&cg=0&cc=1&si=http%3A//games.espn.com/ffl/clubhouse%3FleagueId%3D424204%26teamId%3D1%26seasonId%3D2017&rp=&ts=compact&rnd=1510540168588 net::ERR_BLOCKED_BY_CLIENT
Image (async)
(anonymous) @ c?js=analytics/sOmni.js,analytics/analytics.js,analytics/externalnielsen.js&xhr=1:2
(anonymous) @ c?js=analytics/sOmni.js,analytics/analytics.js,analytics/externalnielsen.js&xhr=1:2

**Comment by flipperbw** [comment]
None of those are me. I think this only breaks midweek for some reason. I'll have to wait until around Wednesday to look again.

**Comment by flipperbw** [comment]
Is this still occurring?

**Comment by williamadba** [comment]
working now!
![bryant 20171205](https://user-images.githubusercontent.com/6641470/33629058-5cd9d518-d9c8-11e7-8cd5-25814f00f3b2.png)
