### ISSUE TITLE
FP columns dont initially show when viewing "my team" in yahoo

### ISSUE THREAD

**Issue by darrinmn9** [flipperbw/FantasyPlus#28]
Thank you for this helpful extension!

I'm using yahoo, and i see the FP columns automatically populated in the "players" and "matchup" tabs, but i don't initially see the columns in the "my team" tab as shown in the image on the chrome devtools extension website. (Within the "my teams" tab, "stats -> week 1" is selected)

If I click "refresh data" on the FP extension icon in chrome, then the columns are added. Is there a relatively easy fix to have these automatically populated without having to manually click "refresh data"?

chrome Version 68.0.3440.106

**Comment by darrinmn9** [comment]
after looking further, there might be another issue here as well.

Initial page, before manually click "refresh data"
![Uploading Screen Shot 2018-08-27 at 1.43.45 PM.png…]()

After clicking "refresh data"
![Uploading Screen Shot 2018-08-27 at 1.44.05 PM.png…]()

It looks like the data from yahoo's "Proj pts" column is added under the Rank (FP) column after i manually refresh the data.

**Comment by bretty-mcbrettface** [comment]
You're correct- I recently changed the way that I handle "watchers" for the various sites, and it seems like Yahoo might have changed itself again. If it doesn't see a valid place to put the columns, it will ignore them and watch the page for changes. But that appears to not be working correctly so I'll take a look asap.

Not sure why the columns are like that - does it work properly on the free agency page?

**Comment by flipperbw** [comment]
You're correct- I recently changed the way that I handle "watchers" for the various sites, and it seems like Yahoo might have changed itself again. If it doesn't see a valid place to put the columns, it will ignore them and watch the page for changes. But that appears to not be working correctly so I'll take a look asap.

Not sure why the columns are like that - does it work properly on the free agency page?

**Comment by darrinmn9** [comment]
so in the free agency tab ("players -> player list") by default the page (at least as of now), is filtered to show 2017 stats (maybe yahoo will change that default once the season starts).

If I change the filter to "week 1 (proj)", the FP columns arent added by default. I either have to refresh the chrome tab, or click "refresh data" on the fp plugin.

I do wonder though, once the season is underway, I believe yahoo defaults the filter to "week 1 (proj)", which may make the FP columns auto populate?

**Comment by flipperbw** [comment]
Okay, I see why it's switched at least. Yahoo is doing something bizarre: they're removing their player videos if you don't navigate directly to the week 1 projections. I have no idea why, but it's there one second, switch tabs, and then it disappears when you go back. I'll keep looking into it.

**Comment by darrinmn9** [comment]
Everything seems to be fixed on yahoo based on ur recent changes. Thank you so much!
